### ISSUE TITLE
Elasticsearch filter not working due to 1 sec indices refresh?

### ISSUE THREAD

**Issue by niksfirefly** [logstash-plugins/logstash-filter-elasticsearch#15]
I am trying to use elasticsearch filter but with no success.
I want to search logs to find past events and add fields to actual event.
I think this is due to 1 sec refresh of indices so when past events are
too close to actual event they are not available.

I tried to:
1.change ES output options in logstash
flush_size => 1
idle_flush_time =>1
2.patched ES filter gem with action
client.indices.stats refresh: true
before search - but that's not working too!!

one working ugly solution - with
sleep(20) 
before search action
in ES filter

what am i doing/thinking wrong?
Is there another solution for searching past events in logstash?

**Comment by webmat** [comment]
Sorry for the delay here.

I understand you were having problems accessing events that were too close in the past, to augment events being processed.

Typically this plugin is used to augment events based on less time-sensitive data (like static or slow changing datasets).

Since you have not looped back on this, I assume this is no longer a problem?

**Comment by webmat** [comment]
Closing this. Let us know or reopen if this is still an issue for you.
