### ISSUE TITLE
Why aren't maintainers merging the index pull requests?

### ISSUE THREAD

**Issue by nzlosh** [logstash-plugins/logstash-filter-elasticsearch#18]
There are at least  5 independent pull requests that implement support for specifying indexes to query against.

Is this an undesirable feature?  What's stopping such a patch from being merged?

**Comment by jordansissel** [comment]
We are still working to ensure we don't lose PRs and provide adequate reviews in a timely fashion.

I don't have a cause for why these PRs haven't been reviewed, so I will not offer excuses. However, if I provide a quick review of the 7 open PRs:

<img width="1130" alt="prs" src="https://cloud.githubusercontent.com/assets/131818/8531586/5f031370-23dd-11e5-9b11-a8d95a6309c0.png">

6 of the 7 open PRs are inelligible for merging because of a failure one of the requirements (tests pass, CLA signed, etc). Looking at the 6 PRs with :x:, all 6 are marked as such due to not having a CLA signed by the authors of the PR. A CLA signature is necessary, but not sufficient, for us to merge code. It has become my practice to not review any code which has not CLA signed for it due to intellectual property tainting concerns - though I am not a lawyer, I try to be safe for myself and the logstash community.

So, assuming we agree with the idea of a given proposed change (a PR), going forward with any of the PRs you wish to have merged will require a minimum of two things:
1. a signed CLA by the author of the patch(es)
2. any patch adding features or fixing bugs should be accompanied with good tests

I haven't checked the 2nd point for any of these PRs while writing this response because the 1st point is unfulfilled.

**Comment by jordansissel** [comment]
Lastly, I do apologize for any delays in reviews or merging of changes. I appreciate you giving us a little poke to tell us where we're slacking. Thank you for helping us stay on track! :)

**Comment by nzlosh** [comment]
Thanks for your feedback and taking the time clarify the steps required to get the pull request into the right state.  I didn't mean to come across abruptly, I was perplexed as to why so many equivalent patches were marked as failed without a direct description stating why.
I've signed a CLA and have re-push the initial pull request using the appropriate email address.

**Comment by juerkan** [comment]
+1

**Comment by roji** [comment]
It's 3 months later and there's still no movement here... Any chance you guys can finally do this??

**Comment by purbon** [comment]
I recently took a maintenance round for this plugin, I apologies for delays.
